//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseTaskEntities : DbContext
    {
        public DatabaseTaskEntities()
            : base("name=DatabaseTaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<SalesPerDays> SalesPerDays { get; set; }
        public virtual DbSet<SalesPerMonth> SalesPerMonth { get; set; }
        public virtual DbSet<SalesPerQuarters> SalesPerQuarters { get; set; }
        public virtual DbSet<SalesPerWeeks> SalesPerWeeks { get; set; }
        public virtual DbSet<SalesPerYears> SalesPerYears { get; set; }
    }
}
